# Generated by Django 3.1.2 on 2020-12-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='building_community_name',
            field=models.CharField(default='no_name_', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_address',
            field=models.CharField(default='no_address_', max_length=255),
        ),
    ]
