# Generated by Django 3.1.2 on 2020-12-23 07:26

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201218_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=accounts.models.customer_image_file_path),
        ),
    ]
